---
abstract: 'Perl extension for dispaying bars in the terminal'
author:
  - 'Gil Gonçalves <lurst@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Spark
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Term::Spark:
    file: lib/Term/Spark.pm
    version: 0.21
requires:
  Sub::Exporter: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/LuRsT/term-spark/issues
  homepage: https://metacpan.org/release/Term-Spark
  repository: git://github.com/LuRsT/term-spark.git
version: 0.21
